sophus/rxso3.hpp
test/core/test_rxso3.cpp

- scale is now represented as quaternion.squaredNorm(); a lot of functions are more efficient since std::sqrt is only called in a few places now
- matrix() and operator* are reimplemented from scratch
- added explicit class invariant that the scale must be >= eps
- group multiplication using saturation so that it obeys class invariant

RxSO3 re-design

---

sophus/common.hpp

Currently, the `SOPHUS_ENSURE` macro uses the gcc extension `##` before `VA_ARGS` to remove the leading comma when `VA_ARGS` is empty.
This gcc extension is not part of iso C99, which causes gcc to give this warning 
`warning: ISO C99 requires rest arguments to be used when called with the flags --pedantic and --std=c99.`
This would in general be safe to ignore, but I am working within a project that has some very strict compilation rules, and treats the warning as errors.
A simple solution is to include the description argument inside the "..." variadic arguments, such that there is always at least one argument as part of the ellipsis.
https://github.com/alvaroabascar/caballa/issues/1
https://stackoverflow.com/questions/4100746/suppressing-iso-c99-requires-rest-arguments-to-be-used

Fix ISO C99 GCC rest error for SOPHUS_ENSURE

---

sophus/so3.hpp

fixes uninitialized Quaternion in SO3::internalGenerator()

set Quaternion coefficients to 0 before setting generator element

---

sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/se2.hpp
sophus/se3.hpp
sophus/sim2.hpp
sophus/sim3.hpp
sophus/so2.hpp
sophus/so3.hpp
sophus/types.hpp
test/core/test_rxso2.cpp
test/core/test_rxso3.cpp
test/core/test_se2.cpp
test/core/test_sim2.cpp
test/core/test_sim3.cpp
test/core/test_so2.cpp
test/core/test_so3.cpp
test/core/tests.hpp

It seems reasonable to have group action on lines that acts compatible with group action on points.
I've added this group action as left-multiply Eigen::ParametrizedLine by the group element.
Multiplication implementation preserves direction norm (where applicable).
Test case checks that image of the line passing through two points passes through their images after applying transformations.

Adding group actions on lines

---

CMakeLists.txt
SophusConfig.cmake.in
test/ceres/CMakeLists.txt
test/core/CMakeLists.txt

I decided to cleanup some of the work @sergiud did on the cmake files, so that his work can be included upstream.
Most notably, Sophus now exports a CMake Config-file Packages file, and can be included in any cmake project with:
```
find_package(Sophus 1.0)
...
target_link_libraries(target Sophus::Sophus)
```
More details about cmake's package system can be found [here](https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html).

Cleanup and modernize CMakeLists.txt

---

CMakeLists.txt
appveyor.yml
sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/se2.hpp
sophus/se3.hpp
sophus/sim2.hpp
sophus/sim3.hpp
sophus/so2.hpp
sophus/so3.hpp
sophus/types.hpp
test/ceres/test_ceres_se3.cpp
test/core/tests.hpp

This PR enhances the operator* for Sophus types in several ways:
1. Allowing product with different derived classes. This allows e.g., SE3Base to multiply with any SE3Base such as Eigen::Map<SE3d>. Previously the operator* required both objects to be the same type, limiting the ability to use concrete objects with maps. This same change was also made for Point multiplication operators.
2. Enable mixing double and ceres::Jet scalars for Sophus object multiplication. ceres::Jet-to-double operations are generally faster than Jet-to-Jet, so the change from 1. also allows multiplying Sophus objects when one object is a ceres::Jet type and the other is a double.
3. Add new operator for Homogeneous Point multiplication. Homogeneous points are a convenient representation for points near infinity …

Extend operator* for Sophus types

---

CMakeLists.txt

To permit early usage of CMAKE_INSTALL_INCLUDEDIR when setting the installed interfaces for the target.
This probably didn't get noticed since most people will be dropping the installed headers into a common include directory shared with other projects.

Upfront GNUInstallDirs

---

package.xml

This allows dropping the directory inside the catkin workspace and building with catkin-tools. I'm not sure if it is actually installable since it probably requires an install rule for package.xml which I'm not sure how to write. But it shouldn't be hard to find.

Added package.xml for catkin-tools compatibility

---

sophus/se2.hpp
sophus/se3.hpp
test/core/test_se2.cpp
test/core/test_se3.cpp

Previously `SE2<T>::setRotationMatrix(...)` did not compile for any type and
`SE3<T>::setRotationMatrix(...)` did not compile for Ceres Jet types.
This commit also adds tests for both setRotationMatrix methods.

Fix setRotationMatrix methods in SE2 and SE3

---

sophus/common.hpp

A #define for M_PI is not guaranteed by the standard, even though many C standard library implementations provide it in math.h. Increase portability by replacing this reference to a non-standard symbol.

Remove M_PI

---

sophus/so3.hpp

This moves any invocation of sqrt(...) into guarded parts of code.
@strasdat please make sure what I'm doing is kosher here

Fix ceres Jet issues with quaternion identity

---

CMakeLists.txt
package.xml

Wondering if we can get a new version tagged for release purposes (I am in the process of re-sync'ing to master and releasing into ROS2 - Eloquent). 
Looks like there has been some minor api changes since the `1.0.0` tag (e.g. [here](https://github.com/strasdat/Sophus/commit/13fb3288311485dc94e3226b69c9b59cd06ff94e#diff-02290733bf2d979ae4aa077aa9bcc555R101), so I've bumped it to `1.1.0` in this PR.
If this is fine, it could also use a `1.1.0` tag made along with this PR.

New version - 1.1.0

---

sophus/so3.hpp
test/core/test_so3.cpp

Hi Hauke!
Two contributions:
- Added a sampling symmetry test that fails for the current implementation of `SO3::sampleUniform()`
- Implemented a probabilistically correct version of `SO3::sampleUniform()`, based on Eigen's implementation linked in #192

Probabilistically correct uniform sampling for SO(3)

---

sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/se2.hpp
sophus/so2.hpp
sophus/so3.hpp
test/core/test_rxso2.cpp
test/core/test_rxso3.cpp
test/core/test_se2.cpp

Introduce new typedef ComplexTemporaryType / QuaternionTemporaryType which can be used for temporary expressions also for Map types, where ComplexType / QuaternionType is also a Map.
Fixes the following bugs and adds regression tests:
- RxSE2/3, Sim2/3: For Map types calling rotationMatrix() wrongly normalizes the stored quaternion.
- RxSE2/3, Sim2/3: For const Map types calling rotationMatrix() doesn't compile.
- SE2: For Map types setRotationMatrix() doesn't compile.
**Update:** Fixed wrong usage of ComplexTemporaryType and add test for setRotationMatrix for Map.

Fix bug with rotationMatrix() / setRotationMatrix() for Map types.

---

sophus/common.hpp
sophus/formatstring.hpp
sophus/test_macros.hpp
test/core/test_common.cpp

This library is being used for embedded applications and as such, iostream is being removed from the build. To accomplish this when building with SOPHUS_DISABLE_ENSURES, the FormatString functionality needed to be moved to a separate file and conditionally included in common.hpp.

Separated FormatString from common.hpp for embedded use

---

CMakeLists.txt

Fix build failure caused by #236

Add formatstring.hpp to SOPHUS_HEADER_FILE

---

sophus/so3.hpp

Seems to be a typo, see https://www.wolframalpha.com/input/?i=series+2+*+atan%28x+%2F+w%29+%2F+x
Presumably has little practical impact though.
References:
* https://github.com/strasdat/Sophus/pull/230#discussion_r326546818
* https://github.com/strasdat/Sophus/issues/186#issuecomment-447566191

Fix Taylor expansion of SO3::logAndTheta

---

sophus/common.hpp

Add a macro to work-around issues with defaulting the constructor in the Eigen Map specializations for Sophus types.

Fix windows cuda builds that use sophus.

---

sophus/interpolate.hpp

When p = 1, interpolate returns foo_T_barz.

Fix function doc for interpolate

---

sophus/common.hpp
sophus/rxso2.hpp
sophus/rxso3.hpp
test/core/test_rxso2.cpp
test/core/test_rxso3.cpp

I would like to discuss a problem with `RxSO2` and `RxSO3` normalization/saturation.
With the previous  implementation user might get assertions from "unlucky" multiplication of group elements.
In case of `RxSO2` a squared norm of complex number is compared with squared epsilon and, if comparison fails, complex number is normalized and multiplied by epsilon.
However, one might note that in IEEE754-2008 arithmetic the action taken does not guarantee that the condition is now satisfied.
One particular example (keep in mind that it is not "specifically crafted", one can get many such examples just by sampling random vectors and checking the condition):
```
Epsilon: 1.0000000000000000e-10 ( bb bd d7 d9 df 7c db 3d )
Epsilon^2: 1.0000000000000001e-20 ( 24 42 92 0c a1 9c c7 3b )
Normalized …
```

RxSO2 and RxSO3 normalization

---

examples/CMakeLists.txt
test/ceres/CMakeLists.txt
test/core/CMakeLists.txt
test/core/test_rxso2.cpp
test/core/test_rxso3.cpp
test/core/tests.hpp

- Complete the change to Ceres 2.0 (see #270); note that the cmake usage of ceres has changed: http://ceres-solver.org/installation.html#version-2-0
- Fix unit test compilation when compiling with ceres (see #267). I tested unit test w/ and w/o ceres.

Complete update to Ceres 2.0 and fix unit tests with Jet

---

sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/sim2.hpp
sophus/sim3.hpp
sophus/sim_details.hpp
test/core/tests.hpp

This pull-request makes `RxSO2`, `RxSO3`, `Sim2` and `Sim3` groups complete in terms of "additional derivatives" (`Group::Dx_this_mul_exp_x_at_0`, `Group::Dx_exp_x` and `Group::Dx_exp_x_at_0` methods).
Since all groups now have the same set of derivative-evaluation methods, `LieGroupTests::additionalDerivativesTest` is enabled for all groups

Additional derivatives for RxSO(2,3) and Sim(2,3) groups

---

sophus/average.hpp
sophus/so2.hpp

Sophus uses a 2-D Eigen type to represent complex numbers. Including `<complex>` in `so2.hpp` is therefore unnecessary.

remove unnecessary SO2 include

---

appveyor.yml

Enables log output for failed tests. For understanding why #282 fails. Also consistent to `scripts/run_cpp_tests.sh`.

ci: enable ctest `--output-on-failure`

---

scripts/run_cpp_tests.sh
sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/se2.hpp
sophus/se3.hpp
sophus/sim2.hpp
sophus/sim3.hpp
sophus/so2.hpp
sophus/so3.hpp
sophus/types.hpp
test/core/test_rxso3.cpp
test/core/test_se3.cpp
test/core/test_sim3.cpp
test/core/test_so3.cpp
test/core/tests.hpp

This pull-request adds left group action on hyper-planes (`Eigen::Hyperplane<Scalar, Dim>`); while for groups acting on 2d-space hyper-planes are just another parameterization of lines, 3d-case is more useful.
The norm of normal vector is preserved since it is used as (unenforced) class-invariant in `Eigen` (for computing distance-to-plane, etc).

Add left group action on hyper-planes

---

sophus/interpolate_details.hpp
sophus/so3.hpp
test/ceres/CMakeLists.txt
test/ceres/test_ceres_so3.cpp

PR #281 and #269 attempted to fix the issue that the automatic differentiated gradient of the `SO3::log()` function is incorrect when the `SO3` object represents a rotation by almost `pi`. Since these PRs were never merged, **this issue persists**. 
This PR revisits the problem, adopting an `atan2` implementation of Hertzberg's _atan-based log_ inspired by Ceres's own `ceres::QuaternionToAngleAxis` in `rotation.h`. [Full details with mathematical derivations are provided in this gist](https://gist.github.com/Hs293Go/7a1bb18f639753c05b8e753089629e50)
- Implemented `test/ceres/test_ceres_so3.cpp` to verify that the autodiff issue is fixed 
- Changed implementation of `hasShortestPathAmbiguity` in `interpolate_details.hpp` to solve an problem also indicated in #269, i.e. `test_so3.cpp` …

Revisit fixing SO3::log() / logAndTheta() when rotation has angle close to pi

---

.github/workflows/coverage.yml
.github/workflows/sympy.yml

With SymPy version 1.9, computing the limits in SO(3) Jacobian results in an error and consequently CI failures. While it is possible to solve the issue by switching to the [Gruntz algorithm](https://docs.sympy.org/latest/modules/series/series.html#the-gruntz-algorithm) for limits computation, other issues arise. Particularly, the code generator produces results varying between SymPy releases. Therefore, the easiest workaround is to pin the SymPy version to the last version known to be working.
Also, the `ubuntu-16.04` runner [has been removed](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/). Switch to `ubuntu-20.04` runner.

fix sympy failures

---

sophus/common.hpp

- This define used to enable the `fmt` macro as an alias to
`FMT_STRING`, but the code uses `FMT_STRING` already anyway,
so it is not needed for any version of libfmt.
- Since libfmt 7.0 this macro has been removed and it has no
effect in any case.
(https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst)
- For older versions, it causes `fmt` to be defined as a macro,
which can break other code and lead to weird error messages,
for example in Pangolin.
(https://github.com/stevenlovegrove/Pangolin/issues/663)

remove unused FMT_STRING_ALIAS (to fix compilation with old libfmt)

---

sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/se2.hpp
sophus/se3.hpp
sophus/sim2.hpp
sophus/sim3.hpp
sophus/so2.hpp
sophus/so3.hpp

- Define copy-assignment operator explicitly. The definition of
implicit copy assignment operator is deprecated in presence of a
user-declared copy constructor (-Wdeprecated-copy in clang >= 13)
- Building with clang-13 fails without this fix (b/c of Werror)
- On macOS, clang from Homebrew is now version 13.
- Explicitly declaring and defaulting should not change the behaviour,
just avoid the deprecation.
Fixes #317

Fix compilation with clang-13 by explicitly defining copy-assignment

---

sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/se2.hpp
sophus/se3.hpp
sophus/sim2.hpp
sophus/sim3.hpp
sophus/so2.hpp
sophus/so3.hpp

- Making them explicit avoids unwanted implicit conversion from
Scalar* to Eigen::Map<Sophus::...<Scalar>>.
- The constructors not yet being explicit might have just been an
oversight.
- Eigen::Map constructors in Eigen are explicit, see e.g.:
- https://gitlab.com/libeigen/eigen/-/blob/0d73440fb212abb778fc7d662fb6a621252feda4/Eigen/src/Core/Map.h#L131
- https://gitlab.com/libeigen/eigen/-/blob/0d73440fb212abb778fc7d662fb6a621252feda4/Eigen/src/Geometry/Quaternion.h#L420

Make Eigen::Map constructors explicit.

---

sophus/rxso2.hpp
sophus/so2.hpp

1. To be consisent with `std::abs(std::complex<>)`, compute the norm in terms of `std::hypot` to avoid numerical inaccuracies.
2. Vectorize the actual normalization.

simplify SO2 normalize

---

sophus/ceres_local_parameterization.hpp
sophus/rxso2.hpp
sophus/rxso3.hpp
sophus/so3.hpp
test/ceres/CMakeLists.txt
test/ceres/test_ceres_rxso2.cpp
test/ceres/test_ceres_rxso3.cpp
test/ceres/test_ceres_se2.cpp
test/ceres/test_ceres_se3.cpp
test/ceres/test_ceres_sim2.cpp
test/ceres/test_ceres_sim3.cpp
test/ceres/test_ceres_so2.cpp
test/ceres/test_ceres_so3.cpp
test/ceres/tests.hpp

* Added templated local parameterization class
* Slightly adjusted `RxSO2::cast` / `(Rx)SO3::operator*` in order to be compatible with `ceres::Jet`
In order to work around a corner-case of `SO2::Tangent` being `Scalar` (and not `Vector<Scalar, 1>`), helper trait `is_mappable_type_v` is introduced (using completeness of `Eigen::internal::traits<T>`, since just having `::Scalar` type is not enough, since `ceres::Jet` has this type defined, but needs to be considered a scalar). This type trait is only needed for group-agnostic code and end-users do not need to use it.
Added also a simple Lie-group averaging example (on a complete graph in order to simplify test data generation).

Templated local parametrization for ceres

---

run_format.sh

The sympy folder contains generated cpp files which we don't want to
auto-format.
This was apparently missed during the py -> sympy folder rename:
4da9a55431ea4cd48ec8a68ad996a2801e288e6a
See: https://github.com/strasdat/Sophus/pull/342#issuecomment-1072592484

ignore sympy folder in run_format.sh

---

CMakeLists.txt

Recent versions of QtCreator only associate header files with the
project that are explicitly mentioned as sources of some
target. Without this change, the Sophus headers were not picked up as
project files. This is a problem, since for example, it breaks the
"clang-format on file save" feature.

cmake: update 'custom' target with all header files

---

scripts/install_linux_deps.sh

Line 23 of `scripts/install_linux_deps.sh` invokes `ccache` which may not be present on the host machine. This PR ensures `ccache` is installed prior. 
Signed-off-by: Yadunund <yadunund@openrobotics.org>

Install ccache via scripts/install_linux_deps.sh

---

CMakeLists.txt

Add new ceres manifold-related files to SOPHUS_HEADER_FILES.
I kept the ceres_local_param file still in there for compatibility. Maybe it can be removed in a future release.
Related to #355

Add missing header files (ceres manifold).

---

test/ceres/CMakeLists.txt
test/core/CMakeLists.txt

Originally, the ceres test CMakeLists.txt only required Ceres 2.0.0.
However, this version doesn't define ceres/manifold, and therefore
when compiling against Ceres 2.0.0 the compilation fails.
See #359 
I don't claim that this is the optimal solution, however it solves the issue for me. It might be useful to reference the necessary Ceres version somewhere in this repo to avoid confusion in the future. As I already had both Eigen and Ceres installed I assumed I didn't have to execute the installation scripts.

Look for Ceres 2.1.0

---

sophus/common.hpp
sophus/geometry.hpp
sophus/interpolate.hpp
sophus/rxso2.hpp
sophus/se2.hpp
sophus/se3.hpp
sophus/so2.hpp
sophus/so3.hpp
sophus/test_macros.hpp
sophus/types.hpp
test/core/test_rxso2.cpp
test/core/test_rxso3.cpp
test/core/tests.hpp

`libfmt` introduces breaking changes in API starting from v9.0.
Multiple types, such as Eigen expressions, templated scalar types were being output via old API that allowed anything `std::ostream<<`'able to be output using just an `{}` format expression and nothing else.
Adding a wrapper into `fmt::streamed` to all arguments of various macros seems to be the simplest way to preserve behavior similar to one that was available with the previous version of `libfmt`

fmt-v9 compatibility

---

cpp/sophus/image/image.h
cpp/sophus/image/image_view.h
cpp/sophus/image/runtime_image.h
cpp/sophus/image/runtime_image_test.cpp
scripts/install_ci_deps_mac.sh
scripts/install_local_deps_mac.sh
scripts/run_cpp_tests.sh

Supported for RuntimeImages using a Variant based ImagePredicate.
Doing this required a small change to the predicate pattern such that the predicate is an non templated struct with a templated static method. This allows querying the variant type without hitting the static assert or needing a particular PixelType to query.

Enable visitation pattern for RuntimeImage

---

.gitmodules

This makes it easier for CI in consuming projects to clone without SSH. 
If you already have the project checked out before this change, you may need to run `git submodule sync` to see this change take effect. Though most users wouldn't notice a difference, this is really to support CI systems.

Unify on https remote urls for submodules

---

cpp/sophus/lie/rxso3.h
cpp/sophus/lie/sim3.h

This is actually all I need, but perhaps it is odd to have assignment without constructor overload? I can add those too if you like.

Add convenience assignment operators for subgroups of rxso3 and sim3.

---

sophus/rotation_matrix.hpp

`Eigen/Dense` contains `Eigen/Core`, `Eigne/Geometry`, `SVD`, etc, which is much expensive to include.
By reducing `Eigen/Dense` to `Eigen/Core` in `sophus/rotation_matrix.hpp`, we can avoid unnecessary headers when using `se3.hpp`, `so3.hpp`, or `rotation_matrix.hpp`. This would help to reduce compilation time for Sophus' users with a large codebase.

Reduce Eigen/Dense to Eigen/Core in sophus/rotation_matrix.hpp

---

sophus/so3.hpp

this saves a useless normalization operation. 
Also this removes spurious changes of numerical behavior when one adapt a codebase to be compatible with both double and float from only one of them. This helps for instance in automatic noop testing on continuous integration system.

Make SO3<Scalar>::cast<Scalar>() a noop

---

sophus/so2.hpp

The constructor of HomogeneousPointProduct expects the three argument to have same type, this is currently not the case when Scalar is a Ceres Jet type.

Fix SO2 when using ceres jet

---

sophus/sim2.hpp
sophus/sim3.hpp

The functions setRotationMatrix() of Sim3 and Sim2 takes a reference instead of a constant reference (currently in Sim3):
```
void Sophus::Sim3Base< Derived >::setRotationMatrix(Matrix3<Scalar>& R);
```
Is there a particular reason? Because its implementation calls `rxso3().setRotationMatrix(R);`, which just needs a constant reference. Using a const reference would be more consistent and convenient.

Make all `setRotationMatrix()` takes constant reference

---

test/core/test_common.cpp

Converted 1.0 and 0.0 to 1 and 0 respectively in the first argument of parent_T_spline(i,u) (and derivative): because this is a knot index argument. It adds nothing to the test itself and is confusing to the reader who wants to check how Sophus splines are used.

Update test_common.cpp: use integer constant for knot index

---

README.md

docs: vcpkg build instructions

---

.github/workflows/main.yml
CMakeLists.txt
examples/CMakeLists.txt
package.xml
scripts/run_cpp_tests_clang.sh
scripts/run_cpp_tests_gcc.sh
setup.py

compiler toolchain tweaks
